import { TariffDto } from "./TariffDto";

export let tariffs: TariffDto[] = [
  {
    name: "Инвестор",
    url: "https://www.tinkoff.ru",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "https://acdn.tinkoff.ru/static/documents/invest-tariff-fees.pdf",
    commissionProcent: 0.003,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "Тинькофф"
  },
  {
    name: "S",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.003,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "Альфа-Банк"
  },
  {
    name: "Инвестор",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.001,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 177,
    minMonthCommission: 0,
    brokerName: "БКС"
  },
  {
    name: "Трейдер",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0006,
    minSumToOpen: null,
    subscriptionFee: 199,
    depositoryFee: 177,
    minMonthCommission: 0,
    brokerName: "БКС"
  },
  {
    name: "Мой онлайн",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0006,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "ВТБ"
  },
  {
    name: "Инвестор стандарт",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00051,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 150,
    minMonthCommission: 0,
    brokerName: "ВТБ"
  },
  {
    name: "Профессиональный стандарт",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00057,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 150,
    minMonthCommission: 0,
    brokerName: "ВТБ"
  },
  {
    name: "FreeTrade",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0001,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "ФИНАМ"
  },
  {
    name: "Консультационный",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00108,
    minSumToOpen: 30000,
    subscriptionFee: 0,
    depositoryFee: 177,
    minMonthCommission: 177,
    brokerName: "ФИНАМ"
  },
  {
    name: "Дневной",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00035,
    minSumToOpen: 30000,
    subscriptionFee: 0,
    depositoryFee: 177,
    minMonthCommission: 177,
    brokerName: "ФИНАМ"
  },
  {
    name: "Самостоятельный",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0006,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "Сбербанк"
  },
  {
    name: "КИТ-Универсал",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0005,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 200,
    brokerName: "КИТ Финанс"
  },
  {
    name: "Стандарт",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00085,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "ГазпромБанк"
  },
  {
    name: "Инвестиционные идеи",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0017,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "ГазпромБанк"
  },
  {
    name: "Первый",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00035,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 150,
    minMonthCommission: 0,
    brokerName: "АТОН"
  },
  {
    name: "Инвестор",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0025,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "ПромСвязьБанк"
  },
  {
    name: "Профессионал",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.003,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "ПромСвязьБанк"
  },
  {
    name: "Всё включено",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0005,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "Открытие"
  },
  {
    name: "Инвестиционный",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00035,
    minSumToOpen: null,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 150,
    brokerName: "Открытие"
  },
  {
    name: "Активный",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0008,
    minSumToOpen: 10000,
    subscriptionFee: 0,
    depositoryFee: 150,
    minMonthCommission: 250,
    brokerName: "АЛОР"
  },
  {
    name: "Фондовый",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00035,
    minSumToOpen: 30000,
    subscriptionFee: 0,
    depositoryFee: 300,
    minMonthCommission: 0,
    brokerName: "IT Invest"
  },
  {
    name: "Стандартный",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00120,
    minSumToOpen: 0,
    subscriptionFee: 0,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "Фридом Финанс (РФ)"
  },
  {
    name: "Все включено",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0,
    minSumToOpen: 0,
    subscriptionFee: 600,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "Фридом Финанс (РФ)"
  },
  {
    name: "Трейдер",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.0005,
    minSumToOpen: 0,
    subscriptionFee: 290,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "Тинькофф"
  },
  {
    name: "Премиум",
    url: "",
    imageUrl: require("../assets/tinkoff-logo.svg"),
    conditionsUrl: "",
    commissionProcent: 0.00025,
    minSumToOpen: 0,
    subscriptionFee: 3000,
    depositoryFee: 0,
    minMonthCommission: 0,
    brokerName: "Тинькофф"
  },
  
];
